### PR TITLE
Single table inheritance

### PR DESCRIPTION
**Pull request by JonnShaft**

### CODE REVIEW

**Comment by NiVanc** [comment]
I just watched the pull request. I don't see the code for the STI. It looks that some of my code for adding models is repeated here. Or am I missing something here?

**Comment by cllns** [comment]
Agreed! There should be a type column: http://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html

**Comment by JonnShaft** [comment]
I added a type column to the create games migration file and adjusted the
pieces model to inherit from the games model (which should be the base
model that inherits from ActiveRecord:Base. Is there additional code needed
to set up STI?

**Comment by cllns** [comment]
Do we want Piece to be a subclass of Game?

**Comment by NiVanc** [comment]
It isn't. The different pieces (pawn, king, queen, ...) will inherit from piece.

**Comment by JonnShaft** [comment]
Got it, I'll adjust the code accordingly ASAP and get it up to GitHub.
Sorry about that.

**Comment by JonnShaft** [comment]
Sorry for the confusion guys. I’m rewriting the code for the STI. I was a bit confused because I did not see any models for the pieces themselves. I’ve added the type column to the create pieces migration file and migrated the changes to the DB.

**Pull request merged**
